### ISSUE TITLE
Refactor willie.irc and willie.bot a bit

### ISSUE THREAD

**Issue by Venti-** [embolalia/willie#296]
The core is a bit of a mess, but nothing that can't be salvaged. I opened this issue to keep track of concrete(ish) ideas of how to possibly improve it without going into burn it to the ground territory.

This issue should be left open for now even if all tasks are done, as the list is not complete. I can implement them at some point, unless there is controversy about the changes, or anyone else can have a stab.

- [x] Remove redundant arguments from `Trigger.__new__`.
- [x] Remove bot as an argument from Origin, unless it's really needed.
- [x] Document the interface for Origin.
- [x] Move nested classes from inside Willie to outside.

**Comment by embolalia** [comment]
@Venti- is there anything more to this, or can we close it?

**Comment by Venti-** [comment]
Nah.
